singer-io/tap-hubspot

tap_hubspot/__init__.py

This pull request fixes an issue where the tap incorrectly fetches company properties as the schema for the deals stream.

Query the proper endpoint to get deal properties

---

tap_hubspot/schemas/subscription_changes.json

As seen in http://developers.hubspot.com/docs/methods/email/get_subscriptions_timeline, `subscriptionId` is a field that is returned when the `changeType` is `SUBSCRIPTION_STATUS`. This is an important field because otherwise we do not know which email the user unsubscribed or subscribed from.

Add subscriptionId to subscription_changes

---

tap_hubspot/__init__.py

Deals that have already been synced in the last 30 days use a different endpoint for a "delta" sync. This endpoint returns the results in a slightly different format, but as it stood, the parser did not account for it. This pull request addresses the issue.

Fix issue with recent deals

---

tap_hubspot/__init__.py

We have a client experiencing 429 errors: https://trello.com/c/NrM1HyB5/1050-cid-101729-pandadoc-singer-hubspot-replication-not-updating-state
HubSpot recommends retrying such errors after a sleep: https://integrate.hubspot.com/t/reaching-secondly-limit/3966/2
This branch makes the tap retry 429 errors 5 times with exponential backoff.
I tested this by making the tap make requests to an endpoint that always returns 429s:
```
INFO Starting sync. Will sync these streams: ['subscription_changes']
INFO Syncing subscription_changes
{"type": "STATE", "value": {"this_stream": "subscription_changes"}}
{"schema": {"type": "object", "properties": {"recipient": {"type": ["null", "string"]}, "timestamp": {"type": ["null", "string"], "format": "date-time"}, "changes": {"type": ["null", "array"], …
```

Retry 429 errors with exponential backoff

---

tap_hubspot/__init__.py

Since free HubSpot accounts only have access to contacts scope, streams outside of scope return 403 errors. If a 403 occurs during a stream's sync, the tap should move on to the next stream.

Handle 403 during stream sync

---

tap_hubspot/__init__.py

Since request is sometimes only called with a url, the unpacking in on_giveup needs to first check to see that there are enough args to unpack.

Check length of args before unpacking

---

tap_hubspot/schemas/email_events.json

These properties only show up in some events and are not listed in the docs, but are quite important.

Added a number of important attributes to the HubSpot tap.

---

tap_hubspot/__init__.py
tests/test_tap_hubspot.py

To avoid tracking more offset state when switching between `companies_all` / `companies_recent`

Exclusively use companies endpoint

---

tap_hubspot/__init__.py

Change up the logic for syncing deals:
* When syncing all deals, add the `properties` query param and check for deals that have been recently modified.
* When syncing recently modified deals, use the `since` query param and check deals modified since the timestamp.

Use since param for recently modified deals or use properties

---

tap_hubspot/__init__.py

datetime.datetime.utcnow actually returns a naive datetime argument. Must manually associate the tzinfo with the object before further processing.

Avoid clock drift in sync entity chunked

---

tap_hubspot/schemas/engagements.json

This fixes an issue that prevents the tap from running in discovery mode due to an invalid schema for the `engagements` endpoint.

Fix/Correct JSON formatting

---

README.md
config.sample.json
tap_hubspot/__init__.py

This PR adds one-step configuration for API key usage, intended to ease the development process. It also updates README to explain API key usage and adds a sample config file to the repo. (This partially addresses issue #9.)
The verbiage in the README was drawn from similar language in the [singer-io/target-csv](https://github.com/singer-io/target-csv/blob/2e76485b2d574594387a945aeb7d6e7df4c43645/README.md) repo.

 Enables use of a HubSpot HAPIKEY for authentication

---

tap_hubspot/__init__.py

This pull request addresses a long-standing issue with list memberships in which memberships are dependent on whether or not a contact has been updated, and thus new dynamic list memberships are frequently not captured.
HubSpot has recently exposed a new pair of fields (`version` & `versionTimestamp`) which are returned when the `includeVersion` query parameter is set to `true` when calling the `contacts` APIs. These new fields track the internal versions of the contacts, which includes updates due to new dynamic list memberships. Updates to other contact properties will also trigger a new `versionTimestamp`, so no prior functionality is lost. Thanks to @jaredmiwilliams for the change.
I've tested a number of scenarios against our dev HubSpot account to confirm functionality, and …

Syncs contacts based on `versionTimestamp`

---

tap_hubspot/__init__.py
tap_hubspot/tests/test_deals.py

PR for this issue https://github.com/singer-io/tap-hubspot/issues/77
Tested with the following stream:
```
{
"streams": [
{
"tap_stream_id": "deals",
"stream": "deals",
"schema": {
"type": ["null", "object"],
"selected": "true",
"additionalProperties": "false",
"properties": {
"portalId": {
"type": [
"null",
"integer"
]
},
"dealId": {
"type": [
"null",
"integer"
],
"selected": "false"
},
"associations": {
"type": ["null", "object"],
"properties": {
"associatedVids": {
"type": ["null", "array"],
"items": {
"type": ["null", "integer"]
}
},
"associatedCompanyIds": {
"type": ["null", "array"],
"items": {
"type": ["null", "integer"]
}
},
"associatedDealIds": {
"type": ["null", "array"],
"items": {
"type": ["null", "integer"]
}
}
}
}
}
},
"metadata": [
{
"metadata": {
"inclusion": "available", …
```

add check for associations

---

tap_hubspot/__init__.py

This is a strange situation that can arise when records are vigorously updated while syncing the engagements stream. There are a few things that contribute to this, given the syncing strategy:
1. There's no way to query based on `lastUpdated`, so the full data set must be inspected each run, and records emitted based on bookmark value.
2. Because of this, the `max_bookmark` is saved through each run and written to state after the whole dataset has been seen.
3. The recordset isn't frozen with the first request, like some pagination strategies, so records may be updated out of the time range as the sync progresses.
**The Situation**
The effect of that is this potential situation:
T0: Start engagements sync
T1: Get record R1 and sync, update max_bookmark to R1[lastUpdated]
T2: Record R1 is …

Add lookback duration for engagements

---

tap_hubspot/__init__.py

Occasionally the tap would receive `429`s, retry `5` times, and then fail.
According to the [Hubspot documentation](https://developers.hubspot.com/apps/api_guidelines), the `429` comes back when we make too many calls in the span of 10 seconds. 
My fix here is to backoff for exactly 10 seconds when we receive the `429`. This was accomplished by changing the backoff strategy from exponential to constant with an interval of 10. To get exactly 10 seconds, the `jitter` was set to `None`.
I also removed the `utils.ratelimit` because in testing, I noticed it was could interfere with the backoff handling.

Change backoff to 10 second intervals

---

tap_hubspot/__init__.py

In [this commit](https://github.com/singer-io/tap-hubspot/commit/c2bb3b00e45d1733f58c07a4d38985a39c859aa5), I added a lookback window to engagements. There's another case where this same sort of thing can happen due to the way the companies API endpoint works (same as engagements, e.g., no sorting, no query-by-updated-at, etc.).
However, depending on the length of each tap-run, the existing pattern won't work across multiple runs, since it doesn't save any state until the end of the stream's sync.
**The Solution Presented Here**
The original pattern was to calculate a lookback window consisting of the `end - start` of the most recent sync. However, this PR modifies that to forcing the bookmark to be the `min(current_sync_start, max_bk_seen)` at the end of a sync, and saving …

Fix Missed Updates Over Multiple Syncs

---

tap_hubspot/__init__.py

When hitting the `deals` endpoint, the tap was always appending all fields nested under `properties` to the request, regardless of whether `properties` was selected or not.  This PR only appends the fields if `properties` is selected.
- Cloned the connection of a customer who was hitting an error because the request url was too long, even though they did not have `properties` selected.  After making the change, their connection no longer hits this error.  Verified that if `properties` is selected, the nested fields are appended and the connection hits the error.
- 

only append properties to deals request if that field is selected

---

CHANGELOG.md
setup.py

bump version to 2.6.4

---

tap_hubspot/__init__.py

On 2/12/20, Hubspot's API started returning a lot more additional properties for the `deals` stream, and appending all of them to requests led to HTTP 414 (url-too-long) errors. Hubspot recommended using the `includeAllProperties = True` and `allPropertiesFetchMode = 'latest_version'` params in the request instead.
- Tested on a multiple cloned connections and the 414 error is resolved
- Hard to verify that this returns ALL the non-null properties the customer has

use includeAllProperties flag for deals

---

CHANGELOG.md
setup.py

bump version to 2.6.5
- none
- none

bump version to 2.6.5

---

.circleci/config.yml
tap_hubspot/__init__.py
tap_hubspot/schemas/deals.json
tap_hubspot/schemas/versions.json
tests/test_hubspot_bookmarks1.py
tests/test_hubspot_bookmarks2.py

Moves properties for certain streams (`deals`, `contacts`, `companies`) to the top level so they are selectable and also keep them nested under `properties`.
Moves versions of data to the top level and nests under `properties_versions`
- 
- 

Move properties fields to top level

---

.circleci/config.yml
setup.py
tap_hubspot/__init__.py
tap_hubspot/tests/test_deals.py
tests/test_hubspot_bookmarks1.py
tests/test_hubspot_bookmarks2.py

The v3 CRM Deals API has `hs_date_entered_*` and `hs_date_exited_*` fields that the v1 Deals API does not have. This PR discovers and syncs those fields.
- Ran the tap
- Low because everything is an addition

Add hs_date_entered/exited fields from v3

---

tap_hubspot/__init__.py
tap_hubspot/schemas/engagements.json
tap_hubspot/tests/test_deals.py
tests/base.py
tests/test_hubspot_all_fields_test.py
tests/test_hubspot_automatic_fields_test.py
tests/test_hubspot_bookmarks1.py
tests/test_hubspot_bookmarks2.py
tests/test_hubspot_discovery.py
tests/test_hubspot_pagination_test.py
tests/test_hubspot_start_date_test.py
tests/unittests/test_deals.py

This PR hits the V3 Deals CRM API to get all `hs_date_entered_*` and `hs_date_exited_*` fields.
The "batch read" endpoint that Hubspot has lets us search for specific IDs. Given that V1 Deals and V3 Deals have the same primary key (`"dealId"` and `"id"` respectively) values, we can merge these new fields into the existing records
- Ran the tap before and after the change to get records
- Diffed the two sets of records
- Lower than #124. The main issue there is we did not paginate the V3 response and could not prove whether the first page of V1 records contains the same IDs as the first page of V3 records. But now that we are searching the V3 for explicit IDs we don't have to worry about that
- revert this branch and bump the version

Add `hs_date_entered_*` and `hs_date_exited_*` fields for the Deals Stream

---

tap_hubspot/__init__.py

This is a bug fix to prevent `429`s from causing the tap to fail
- Ran the tap
- Low, the tap works most of the time

Copy backoff logic from V1 requests

---

tap_hubspot/__init__.py
tests/test_hubspot_all_fields_test.py

In order to get the extra fields from the V3 Deals API, we make a `POST` with (up to) 100 Deal `id`s and the `hs_date_entered_*`, `hs_date_exited_*`, and `hs_time_in_*` fields marked as selected.
The shape of this `POST` body is:
```
{
"inputs" : [<deal ids>],
"properties": [<fields>]
}
```
However, this `properties` list can get too long and Hubspot will return a `500`.
In testing, I noticed that:
* If you leave out the `properties` key, then some default set of fields is returned
* If you ask for any other field, then every non-null field on that deal is returned
* If you ask for a field that does not exist on the deal, then you get back `<key> : null`
Also in testing, I noticed that asking for more than 1000 properties may or may not return a `500`. But looking at the response (and …

Fix `500`s from V3 Deals

---

tap_hubspot/__init__.py

Fixes a bug where this was turning a string into `['h', 'e', 'l'. 'l'. 'o']`
- 
- 

Send a list to the v3 batch read endpoint

---

tests/test_hubspot_all_fields_test.py

New field was returned from deals endpoint.
Field was accounted for in test and carded out.
- 
- 

account for all_assigned_business_unit_ids in deals

---

.circleci/config.yml
tests/test_hubspot_all_fields_test.py

stitch validate json relative path instead of python 3.5 virtual env hardcoded path
- 
- 

stitch validate json relative path instead of python 3.5 virtual env hardcoded path

---

.circleci/config.yml

Use the tap_tester_sandbox environment and move the build time to avoid collisions.
- 
- 

use proper env and move build time

---

tests/test_hubspot_child_stream_only.py

Implement https://jira.talendforge.org/browse/TDL-14966
When a child stream is selected without its parent (usually not allowed via field selection but can be in this case) it will cause a critical error.  We must ensure the error has a message to the user that is sufficient that they can resolve the problem on their own be selecting the parent stream
- 
- 

add a test to check for child streams without parent streams selected

---

tests/client.py
tests/test_hubspot_all_fields_test.py

Companies stream was not getting the correct expected records because we were using recent companies API instead of getting all companies, then filtering.
- 
- 

updated expected records for companies to filter after getall

---

tests/test_hubspot_all_fields_test.py

Drop the `contacts_by_company` stream from the all fields test.
- 
- 

skip the  stream

---

.circleci/config.yml

https://jira.talendforge.org/browse/TDL-16944
Move build time to avoid conflicts with contractors and internal teams.
6:00am UTC -> 1:00 UTC (8:00pm EST, 6:30am IST)
Move slack notifications to new channel.
- 
- 

move runtime and  notifcations

---

tests/test_hubspot_start_date.py

The records for our `owners` in the tap-hubspot account were updated causing a failing test. 
`(tap-tester) vagrant@vagrant:/opt/code/tap-tester$ jq 'select(.table_name == "owners") | .messages[].data.updatedAt' /tmp/tap-tester-target-out.json
"2022-02-11T16:11:14.058000Z"
"2021-12-10T16:21:40.778000Z"`
We moved the start date forward to maintain test coverage for the failing `owners` stream.
- 
- 

move start date to reflect changing test data

---

tests/client.py

Adjust CRUD client method in tests. The `forms` address field was causing a 400 error. It is no longer supported by the v2 endpoint we are hitting.
- Ran client_tester.py locally to confirm root cause was the `create_forms` method. Test passing.
- None, test client change.

Comment out Address Field on form create

---

tests/test_hubspot_all_fields.py

Skipping newly returned `property_hs_latest_source_timestamp` field on `contacts` stream
- Updated linked jira ticket 
- 

skip new property field for contacts stream

---

tap_hubspot/__init__.py
tap_hubspot/schemas/contacts.json
tests/test_hubspot_all_fields.py
tests/test_hubspot_automatic_fields.py
tests/test_hubspot_bookmarks.py
tests/test_hubspot_discovery.py

- Added `versionTimestamp` in the schema of the contacts stream.
- Added `versionTimestamp` in the record of the contacts stream.
- Updated integration test cases.
- Run the discover mode and verify that versionTimestamp field available in the schema of contacts stream in the catalog.
- Run sync mode and verify that versionTimestamp  field is available in each record of the contacts stream.
- Run sync mode with state and verify that the contacts stream respected the bookmark value.
- 

TDL 19241 add version timestamp in contacts

---

.circleci/config.yml
README.md
config.sample.json
tap_hubspot/__init__.py
tap_hubspot/schemas/contacts.json
tap_hubspot/tests/unittests/test_request_timeout.py
tests/test_hubspot_all_fields.py
tests/test_hubspot_automatic_fields.py
tests/test_hubspot_bookmarks.py
tests/test_hubspot_discovery.py

Crest master

---

tests/client.py
tests/client_tester.py

Fix the engagements post method in the test client by dynamically grabbing a contact id to make an association on. 
- 
- 

fix test client post for engagments

---

tap_hubspot/__init__.py
tap_hubspot/tests/unittests/test_get_start.py

To use bookmark of existing connection we have updated code as below,
- Updated get_start function to use older bookmark key value if it is available for any existing connection.
- If the current bookmark_key is available in the state, then get_start returns the bookmark_key value.
- If it is not available then check and return the older_bookmark_key(if it is available) in the state for the existing connection.
- If non of the key available in the state for a particular stream, then return start_date.
- Added unit test cases for the get_start function.
**Note**: We will not clear out existing bookmarks from the state. Instead, we will keep both bookmark values older and newer. 
- Run the sync mode without state and verify that the state file contains only property_hs_lastmodifieddate.
- …

Utilize bookmark of existing connection

---

tests/test_hubspot_all_fields.py

Add the `limitExempt` field to `contact_lists` stream's known missing fields.
- 
- 

add limitExempt to all fields test workaround

---

tests/base.py
tests/client.py
tests/test_hubspot_pagination.py

The pagination test over [here](https://circleci.com/gh/singer-io/tap-hubspot/7869) and [here](https://circleci.com/gh/singer-io/tap-hubspot/7881) are failing with the status code 401. The expiry time of the access_token has been bought down from 6 hours to 30 minutes.
- To overcome the above failure, added refresh logic for access token after every 20 minutes (approx.)
- Add page limit size (250 the maximum API allows) for streams - `contact_lists` and `engagements`. Initially, it had a default of 100. This change will improve the integration test execution time in CircleCI.
Jira - [TDL-21142](https://jira.talendforge.org/browse/TDL-21142)
**NOTE** - This PR contains the changes only for integration tests.
- No risks to any customers.

Refresh the access token after certain interval of time within integration tests

---

tests/test_hubspot_all_fields.py

Add scheduledTasks to known missing fields dict as part of TDL-14997 to allow tier 1 regression to still run and pass until issue is resolved.
- 
- 

 TDL-14997 Add scheduledTasks to known missing fields dict

---

tests/base.py
tests/client.py
tests/test_hubspot_interrupted_sync.py
tests/test_hubspot_interrupted_sync_offset.py

- Add the get, create, and update functionality in client.py
- Update base.py and test cases
**Note** - Dependent on #https://github.com/stitchdata/environments/pull/764
- All integration tests are passed on dev-vm.
- 

Integration tests for newly added tickets stream

---

tap_hubspot/__init__.py
tap_hubspot/tests/test_deals.py
tests/test_hubspot_bookmarks.py
tests/test_hubspot_interrupted_sync_offset.py

To handle records updated between start of the table sync and the end, store the current sync start in the state and not move the bookmark past this value.
- 
- 

Fix bookmarking late record updates during sync

---

CHANGELOG.md
setup.py
tap_hubspot/__init__.py
tap_hubspot/tests/test_deals.py
tests/test_hubspot_bookmarks.py
tests/test_hubspot_interrupted_sync_offset.py

For following streams, stream records were missed which were updated during stream was syncing.
- contacts
- contact_lists
- deals
- forms
- owners
- tickets
- workflows
Implemented a fix to bookmark minimum of stream sync start time and max. modifiedTime.
e.g.
Consider a scenario,
1. 1st sync started at 100 for vids 1-100 and completed in 5 seconds. (`max. modified_time=99`)
2. 2nd sync started at 105 for vids 101-200 and completed in 5 seconds. (`max. modified_time=103`)
3. While 2nd sync was in-progress, `vid_50` and `vid_250` got updated with 106 and 108 respectively.
4. Last sync started at 110 for vids 201-300 and completed in 5 seconds. (`max. modified_time=108`)
With existing implementation, after completion of sync, we set `bookmark_value=108`. This will miss the record `vid_50` …

use sync start time to bookmark contacts stream

---

tests/test_hubspot_start_date.py

fix start-date test by changing the start date for second sync
- 
- low

fix start-date test by changing the start date for second sync

---

CHANGELOG.md
setup.py
tap_hubspot/__init__.py

Multiple clients received a 500 error from hubspot for the engagements table. Although the page limit max is 250 and works for most connections, hubspot advised to lower the page limit which fixed the 500 error. 
This pr adds lowers the page limit and an advanced option to make the page limit for the engagements table configurable. 
- tested with and without the advanced option set
- low

use engagements page size advanced option

---

tests/client.py
tests/test_hubspot_bookmarks.py

https://jira.talendforge.org/browse/TDL-20939
The change is to add more logging to decide on further steps to a discrepancy in bookmark test that occurs occassionally in stream contacts.
Log the time difference between the post message and the create time when a record is created to decide if we want to have a lookback window.
- 
- 

Log the time difference of create time and post time

---

tests/test_hubspot_all_fields.py

https://jira.talendforge.org/browse/TDL-24758
Added 'property_hs_v2_date_entered_appointmentscheduled' to bad_prefixes and
added 'property_hs_is_active_shared_deal' to known_missing_fields
- 
- 

Added new fields to missing and bad_prefixes

---

CHANGELOG.md
setup.py
tap_hubspot/__init__.py

This PR fixes the out-of-index error observed in PR #250.
- 
- 

Patch to fix out of index error

---

tap_hubspot/__init__.py
tap_hubspot/tests/unittests/test_tickets.py

- Created a new function to encapsulate the common logic shared by the ticket and owners streams.
- Updated the ticket and owners streams to utilize the new function.
- Corrected the replication methods for streams - `forms`, `workflows`, `contact_lists` and `engagements`.
- Verified that the refactored code maintains the same functionality as before.
- 

Refactor the code and Correct Replication Methods

---

CHANGELOG.md
setup.py
tap_hubspot/__init__.py
tap_hubspot/tests/unittests/test_custom_objects.py
tests/base.py
tests/base_hubspot.py
tests/client.py
tests/test_hubspot_all_fields.py

This PR addresses an issue where `custom objects` in HubSpot can have the same names as `standard objects` (e.g., contacts, campaigns), leading to extraction failures [TDL-26380](https://jira.talendforge.org/browse/TDL-26380). 
The fix involves renaming custom objects that share names with standard objects to a distinct `custom_object_<standard_object_name>`. This ensures that custom objects are clearly differentiated from standard objects, preventing conflicts and extraction issues.
- 

Tdl 26414 rename custom objects

---

CHANGELOG.md
setup.py
tap_hubspot/__init__.py
tests/client.py
tests/test_hubspot_all_fields.py
tests/test_hubspot_interrupted_sync_offset.py
tests/unittests/test_deals.py

In the tap-HubSpot integration, we currently fetch the properties schema dynamically for certain streams, including contacts and deals. Starting from [November 20](https://developers.hubspot.com/changelog/upcoming-sunset-of-pipeline-legacy-stage-calculated-properties-for-contacts-and-deals?utm_campaign=App%20Partner%20Comms%202024&utm_medium=email&utm_content=326637210&utm_source=hs_email), certain API properties will no longer be returned.
- hs_lifecyclestage_{stage id}
- hs_date_entered_{stage id}
- hs_date_exited_{stage id}
- hs_time_in_{stage id}
Instead, we will need to rely on the new set of properties.
- hs_v2_date_entered_{stage_id}
- hs_v2_date_exited_{stage_id}
- hs_v2_latest_time_in_{stage_id}
- Hs_v2_cumulative_time_in_{stage_id}
Since these are dynamic properties, we have …

TDL-26642: Support new properties foe deals stream
